---
prompt_file: prompts/asqa_default.json
eval_file: data/asqa_eval_gtr_top100_reranked_oracle.json
shot: 2
ndoc: 5
dataset_name: asqa
tag: oracle
model: baichuan4-turbo
custom_api: true
my_api_url: https://api.baichuan-ai.com/v1/chat/completions
my_api_key: sk-84105483f548e0855736af7cbdd79150
max_length: 16384