---
prompt_file: prompts/asqa_default.json
eval_file: data/asqa_eval_gtr_top100_reranked_oracle.json
shot: 2
ndoc: 5
dataset_name: asqa
tag: oracle
model: deepseek-v3
custom_api: true
my_api_url: http://
my_api_key: 
max_length: 16384
