---
prompt_file: prompts/asqa_default.json
eval_file: data/asqa_eval_gtr_top100.json
shot: 2
ndoc: 20
dataset_name: asqa
tag: gtr
model: Llama3.3_70B
flask_api: true
my_api_url: http://
max_length: 16384
