---
prompt_file: prompts/asqa_default.json
eval_file: data/asqa_eval_dpr_top100.json
shot: 2
ndoc: 20
dataset_name: asqa
tag: dpr
model: deepseek-v3
custom_api: true
my_api_url: http://
my_api_key: 
max_length: 16384
