---
prompt_file: prompts/asqa_default.json
eval_file: data/asqa_eval_dpr_top100.json
shot: 2
ndoc: 20
dataset_name: asqa
tag: dpr
model: glm_4_9B_chat
flask_api: true
my_api_url: http://101.132.252.74:20013/proxy_generate
max_length: 16384
