---
prompt_file: prompts/eli5_default.json
eval_file: data/eli5_eval_bm25_top100_reranked_oracle.json
shot: 2
ndoc: 5
dataset_name: eli5
tag: oracle
model: moonshot-v1-32k
custom_api: true
my_api_url: https://api.moonshot.cn/v1/chat/completions
my_api_key: sk-RSwjF2Nb3vAC5MyI5jgsWZLCLJwoF2Ro7EyCcUpSwXtJcPg2
max_length: 16384
