---
prompt_file: prompts/eli5_default.json
eval_file: data/eli5_eval_bm25_top100_reranked_oracle.json
shot: 2
ndoc: 5
dataset_name: eli5
tag: oracle
model: ep-20250123113406-7vzr5
custom_api: true
my_api_url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
my_api_key: 0608ec35-fca7-4552-b8ef-7434a8ad3652
max_length: 16384