---
prompt_file: prompts/eli5_default.json
eval_file: data/eli5_eval_bm25_top100.json
shot: 2
ndoc: 20
dataset_name: eli5
tag: bm25
model: baichuan4-turbo
custom_api: true
my_api_url: https://api.baichuan-ai.com/v1/chat/completions
my_api_key: 
max_length: 16384
