---
prompt_file: prompts/eli5_default.json
eval_file: data/eli5_eval_bm25_top100.json
shot: 2
ndoc: 20
dataset_name: eli5
tag: bm25
model: deepseek-v3
custom_api: true
my_api_url: http://123.129.219.111:3000/v1/chat/completions
my_api_key: sk-FTJ9M5kA8dbynz26fvJHbJMpHKPF7ny9s2Xy9gjZ8OJHWtFI
max_length: 16384