---
prompt_file: prompts/eli5_default.json
eval_file: data/eli5_eval_bm25_top100_reranked_oracle.json
shot: 2
ndoc: 5
dataset_name: eli5
tag: oracle
model: Llama3.3_70B
flask_api: true
my_api_url: http://
max_length: 16384
