---
prompt_file: prompts/eli5_default.json
eval_file: data/eli5_eval_bm25_top100.json
shot: 2
ndoc: 20
dataset_name: eli5
tag: bm25
model: Qwen2_57B
flask_api: true
my_api_url: http://101.132.252.74:20013/proxy_generate
max_length: 16384
